const plantas = [
    {
        id: 1, 
        nombre: "ALOCASIA CUPRE",
        precio: 100,
        imagen: "https://www.mygarden.com.co/wp-content/uploads/2020/05/PLANTA-ALOCACIA-CUPREA-.jpg",
        categoria:"calathea",
        stock: true,       
    },
    {
        id: 2, 
        nombre: "AFELANDRA",
        precio: 150,
        imagen: "https://www.mygarden.com.co/wp-content/uploads/2020/01/PLANTA-APHELANDRA-2-.jpg",
        categoria:"calathea",
        stock: true,       
    },
    {
        id: 3, 
        nombre: "BURLE MARXII",
        precio: 100,
        imagen: "https://www.mygarden.com.co/wp-content/uploads/2020/05/PLANTA-CALATHEA-BURLE-MARXII.jpg",
        categoria:"calathea",
        stock: true,       
    },
    {
        id: 4, 
        nombre: "FREDDIE",
        precio: 100,
        imagen: "https://www.mygarden.com.co/wp-content/uploads/2020/05/PLANTA-CALATHEA-FREDDIE-2-.jpg",
        categoria:"calathea",
        stock: true,       
    },
    {
        id: 5, 
        nombre: "ANTURIO HOLANDES",
        precio: 100,
        imagen: "https://www.mygarden.com.co/wp-content/uploads/2020/05/PLANTA-ANTURIO-ANARANJADO.jpg",
        categoria:"flor",
        stock: true,       
    },
    {
        id: 6, 
        nombre: "BEGONIA",
        precio: 100,
        imagen: "https://www.mygarden.com.co/wp-content/uploads/2020/05/PLANTA-BEGONIA-SEMPERFLORENS.jpg",
        categoria:"flor",
        stock: true,       
    },
    {
        id: 7, 
        nombre: "HORTENSIA",
        precio: 100,
        imagen: "https://www.mygarden.com.co/wp-content/uploads/2020/08/HORTENSIA-PLANTA.jpg",
        categoria:"flor",
        stock: true,       
    },
    {
        id: 8, 
        nombre: "ALBAHACA",
        precio: 100,
        imagen: "https://www.mygarden.com.co/wp-content/uploads/2020/05/PLANTA-AROMATICA-ALBAHACA-MORADA-2-.jpg",
        categoria:"aromaticas",
        stock: true,       
    },
    {
        id: 9, 
        nombre: "LAVANDA",
        precio: 100,
        imagen: "https://www.mygarden.com.co/wp-content/uploads/2020/05/PLANTA-LAVANDA.jpg",
        categoria:"aromaticas",
        stock: true,       
    },
    {
        id: 10, 
        nombre: "HIERBABUENA",
        precio: 100,
        imagen: "https://www.mygarden.com.co/wp-content/uploads/2020/01/HIERBABUENA.png",
        categoria:"aromaticas",
        stock: true,       
    },
]